#define 
git:
  depth: 3

language: csharp
solution: NetCoreSample.sln
sudo: required  
dist: trusty  

env:
  matrix:
    - DOTNET_BUILD=1 CLI_VERSION=latest DOTNET_INSTALL_DIR="$PWD/.dotnetcli" PATH="$DOTNET_INSTALL_DIR:$PATH"
    - NODE_BUILD=1

mono:  
  - 4.2.3
os:  
  - linux

# safelist, only build theses branches
branches:
  only:
  - master
  - dev

before_install:
  - chmod +x ./scripts/dotnetbuild.sh
  - |
    if [[ "${DOTNET_BUILD+x}" ]]; then
      sudo apt-get install -y gettext libcurl4-openssl-dev libicu-dev libssl-dev libunwind8 zlib1g
    fi

install:
  - |
    if [[ "${DOTNET_BUILD+x}" ]]; then
      curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
    fi
  - |
    if [[ "${NODE_BUILD+x}" ]]; then
      nvm install stable
      nvm use stable
      pushd ./src/ITI.PrimarySchool.WebApp/App/primary-school && yarn && popd
    fi

script:  
  - |
    if [[ "${DOTNET_BUILD+x}" ]]; then
      ./scripts/dotnetbuild.sh
    fi
  - |
    if [[ "${NODE_BUILD+x}" ]]; then
      pushd ./src/ITI.PrimarySchool.WebApp/App/primary-school && yarn build && popd
      #js test
    fi

#deploy
#cleanup
#publish

notifications:
  email:
    recipients:
      - kore@intechinfo.fr
      - vanbutsele@intechinfo.fr
    on_success: always
    on_failure: always