git:
  depth: 3

#switch to node as default next time
language: csharp
solution: NetCoreSample.sln
sudo: required
dist: trusty
env:
  matrix:
  - DOTNET_BUILD=1 CLI_VERSION=latest DOTNET_INSTALL_DIR="$PWD/.dotnetcli" PATH="$DOTNET_INSTALL_DIR:$PATH"
  - NOD E_BUILD=1
  global:
  # GITHUBKEY
  - secure: "tf9roE/dA/GSildNjjCz++Xy1T3v/hpiorQMWUFteF6M56Ss/E36f+HHupPKg8zRTmabutFmJBO3appmTDfx0vFWTEdy4oRP7m8oKV1iDP+9XvzQf+ls5LY5WdtbNhTbyr0KkcA0gtspt828gstW6lMu5YtnZKx02ev/difgEBW99zVDR8P+MTAG86XaHv9hcuKYDL809wxnjOBrmGQkQWuOjlAVEkxWSNIbQdA4cdnYjys+g8Yul18/ZpHEoWt+IT+3Y6W5RE8hgENvIMlyGCyaqFbA9ujY2wYNgxi3/K3qE0uByu4bmQH6tqPdebsPUSeYHqAFbJY7veoX8iAWBKh7YmFvIcKItcFNj3GLjfcn78l+yrVqD/5IluNlt5EPf7jwlLweljuQ2WUu4Tj0bxO9q33qgrjidXjkk6HBXxOO2Qif6OxvT+0GNF9S+Upb6VUcf/cG/ULObzwOC+rLolSoZODoHCx1I+X0aGo9dqpAR1qJW54IcXsvNs8TuSErJYQqxHO3GUW0pOTVObv+Xi2Xcd8t1FMn9jaJkLQLrOwhG5flefwpP3rNqPSZ0XviF0CQEz5O69pLq+T0jTtAAmKhCBAeBbt64qYNiwkXUSRkSKdlc5n7B8MpbbIIY4FgF30qSX4SXBJXvy9/GpWERuzvvbtK5O7N6DnZ1x4vdVQ="
  - GIT_DEPLOY_REPO=https://$GITHUBKEY@github.com/ITILostTime/ArchitectureBuildTest.git
  - DOTNET_CLI_TELEMETRY_OPTOUT=1

mono:
- 4.2.3
os:
- linux

branches:
  except:
  - branchNonBuilded
  only:
  - release
  - dev

before_install:
#check if we are not not a TAG or not on Branch : release or dev : leave the build
#- if [ -z "$TRAVIS_TAG" ]; then if [ "$TRAVIS_BRANCH" != "release" ]; then if [ "$TRAVIS_BRANCH" != "dev" ]; then exit 0; fi fi fi
- chmod +x ./scripts/dotnetbuild.sh
- chmod +x ./scripts/set_tags.sh
- |
  if [[ "${DOTNET_BUILD+x}" ]]; then
    sudo apt-get install -y gettext libcurl4-openssl-dev libicu-dev libssl-dev libunwind8 zlib1g
  fi

install:
- |
  if [[ "${DOTNET_BUILD+x}" ]]; then
    curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  fi
- |
  if [[ "${NODE_BUILD+x}" ]]; then
    nvm install stable
    nvm use stable
    pushd ./src/ITI.PrimarySchool.WebApp/App/primary-school && yarn && popd
  fi

script:
- |
  if [[ "${DOTNET_BUILD+x}" ]]; then
    ./scripts/dotnetbuild.sh
  fi
- |
  if [[ "${NODE_BUILD+x}" ]]; then
    pushd ./src/ITI.PrimarySchool.WebApp/App/primary-school && yarn build && popd
    #js test
  fi

#set tag version based on the file at the root of the system
after_success:
- ./scripts/set_tags.sh

before_deploy:
- echo "deploying to GitHub releases"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $GITHUBKEY
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/artifacts/*"
  on:
    tags: true
    repo: ITILostTime/ArchitectureBuildTest
    
notifications:
  email:
    recipients:
    - kore@intechinfo.fr
    - vanbutsele@intechinfo.fr
    on_success: always
    on_failure: always
