#define 
git:
  depth: 3

language: csharp  
solution: NetCoreSample.sln
sudo: required  
dist: trusty  

env:
  matrix:
    - DOTNET_BUILD=1 CLI_VERSION=latest DOTNET_INSTALL_DIR="$PWD/.dotnetcli" PATH="$DOTNET_INSTALL_DIR:$PATH"
    - NODE_BUILD=1

addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:  
  - 4.2.3
os:  
  - linux

# safelist, only build theses branches
branches:
  only:
  - master
  - dev

before_install:
  - chmod +x ./scripts/dotnetbuild.sh

install:
  - |
    if [[ -z "${DOTNET_BUILD+x}" ]]; then
      curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
    fi
  - |
    if [[ -z "${NODE_BUILD+x}" ]]; then
      nvm install stable
      nvm use stable
      cd ./src/ITI.PrimarySchool.WebApp/App/primary-school && yarn
    fi

#  - yarn

#cache:
#  yarn: true

script:  
  - |
    if [[ -z "${DOTNET_BUILD+x}" ]]; then
      ./scripts/dotnetbuild.sh
    fi
  - |
    if [[ -z "${NODE_BUILD+x}" ]]; then
      cd ./src/ITI.PrimarySchool.WebApp/App/primary-school && yarn build
    fi
